### ISSUE TITLE
t-step works wrong on negative values?

### ISSUE THREAD

**Issue by skapral** [typography-gang/typographist#73]
Version: 3.0.3

Typographist produces same font-size values for, let's say, `t-step(2)` and `t-step(-2)`.
Shouldn't it be like in a picture?

[![](https://raw.githubusercontent.com/typography-gang/typographist/master/docs/images/msunit.jpg)](https://raw.githubusercontent.com/typography-gang/typographist/master/docs/images/msunit.jpg)

**Comment by maxinakenty** [comment]
Sergey, thank you for your attention. It should be like in the picture.

**Comment by maxinakenty** [comment]
Sergey, the bug is eliminated. Now everything is as in the image.

**Comment by skapral** [comment]
Thanks
